version: "3.3"
services:
  blog:
    image: "asarkar/non-compos-mentis"
    ports:
      - "4000:4000"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4000"]
      interval: 30s
      timeout: 5s
      retries: 3
