#!/usr/bin/env bash
set -e # halt script on error

bundle install --gemfile=site/Gemfile
BUNDLE_GEMFILE=site/Gemfile bundle exec jekyll build -s site -d public
htmlproofer --alt-ignore '/.*/' --empty-alt-ignore --allow-hash-href --disable-external public
